In [1]:
from secedgar.cik_lookup import get_cik_map
import requests
import numpy as np
import pandas as pd
import time
import io

USER_AGENT = "Academic Research Project (gig-economy-capstone@umich.edu)"

c:\Python311\Lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.4.0) or chardet (6.0.0.post1)/charset_normalizer (3.4.2) doesn't match a supported version!
  warnings.warn(

In [2]:
upwk_cik = '1627475'
cik_padded = str(upwk_cik).zfill(10)

cik_padded = upwk_cik.zfill(10)
url = f"https://data.sec.gov/api/xbrl/companyfacts/CIK{cik_padded}.json"

headers = {
    'User-Agent': USER_AGENT,
    'Accept-Encoding': 'gzip, deflate'
}

response = requests.get(url, headers=headers, timeout=30)
response.raise_for_status()
data = response.json()

results = []
facts = data.get('facts', {})

# US-GAAP namespace contains most financial data
us_gaap = facts.get('us-gaap', {})
# all available metrics in the us-gaap namespace
available_metrics = list(us_gaap.keys())
print(f"Available metrics for CIK {cik_padded}: {available_metrics}")

# all available units
available_units = set()
for metric, metric_data in us_gaap.items():
    for unit in metric_data.get('units', {}):
        available_units.add(unit)
print(f"Available units for CIK {cik_padded}: {available_units}")

Available metrics for CIK 0001627475: ['AccountsPayableCurrent', 'AccountsReceivableGrossCurrent', 'AccountsReceivableNetCurrent', 'AccretionAmortizationOfDiscountsAndPremiumsInvestments', 'AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment', 'AdditionalPaidInCapitalCommonStock', 'AdjustmentsToAdditionalPaidInCapitalEquityComponentOfConvertibleDebtSubsequentAdjustments', 'AdjustmentsToAdditionalPaidInCapitalSharebasedCompensationRequisiteServicePeriodRecognitionValue', 'AdjustmentsToAdditionalPaidInCapitalStockIssuedIssuanceCosts', 'AdjustmentsToAdditionalPaidInCapitalWarrantIssued', 'AdvertisingExpense', 'AllocatedShareBasedCompensationExpense', 'AllowanceForDoubtfulAccountsReceivable', 'AllowanceForDoubtfulAccountsReceivableCurrent', 'AllowanceForDoubtfulAccountsReceivableWriteOffs', 'AmortizationOfFinancingCosts', 'AmortizationOfIntangibleAssets', 'AntidilutiveSecuritiesExcludedFromComputationOfEarningsPerShareAmount', 'AssetImpairmentCharges', 'Assets', 'AssetsCurrent', 'AssetsFairValueDisclosure', 'CapitalExpendituresIncurredButNotYetPaid', 'CapitalizedComputerSoftwareAdditions', 'CapitalizedComputerSoftwareAmortization1', 'CapitalizedComputerSoftwareNet', 'CapitalizedCostsAssetRetirementCosts', 'Cash', 'CashAndCashEquivalentsAtCarryingValue', 'CashAndCashEquivalentsFairValueDisclosure', 'CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents', 'CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsIncludingDisposalGroupAndDiscontinuedOperations', 'CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect', 'CommercialPaperAtCarryingValue', 'CommonStockCapitalSharesReservedForFutureIssuance', 'CommonStockParOrStatedValuePerShare', 'CommonStockSharesAuthorized', 'CommonStockSharesIssued', 'CommonStockSharesOutstanding', 'CommonStockValue', 'ContractWithCustomerLiabilityCurrent', 'ContractWithCustomerLiabilityNoncurrent', 'ContractWithCustomerLiabilityRevenueRecognized', 'CostOfGoodsAndServicesSold', 'CostOfRevenue', 'CumulativeEffectOfNewAccountingPrincipleInPeriodOfAdoption', 'CurrentFederalTaxExpenseBenefit', 'CurrentForeignTaxExpenseBenefit', 'CurrentIncomeTaxExpenseBenefit', 'CurrentStateAndLocalTaxExpenseBenefit', 'DebtInstrumentCarryingAmount', 'DebtInstrumentRedemptionPricePercentageOfPrincipalAmountRedeemed', 'DebtInstrumentUnamortizedDiscount', 'DebtInstrumentUnamortizedDiscountPremiumAndDebtIssuanceCostsNet', 'DebtWeightedAverageInterestRate', 'DeferredFederalIncomeTaxExpenseBenefit', 'DeferredFinanceCostsNet', 'DeferredForeignIncomeTaxExpenseBenefit', 'DeferredIncomeTaxExpenseBenefit', 'DeferredIncomeTaxLiabilities', 'DeferredOfferingCosts', 'DeferredStateAndLocalIncomeTaxExpenseBenefit', 'DeferredTaxAssetsGross', 'DeferredTaxAssetsInProcessResearchAndDevelopment', 'DeferredTaxAssetsLiabilitiesNet', 'DeferredTaxAssetsNet', 'DeferredTaxAssetsOperatingLossCarryforwards', 'DeferredTaxAssetsOperatingLossCarryforwardsSubjectToExpiration', 'DeferredTaxAssetsPropertyPlantAndEquipment', 'DeferredTaxAssetsTaxDeferredExpenseCompensationAndBenefitsShareBasedCompensationCost', 'DeferredTaxAssetsTaxDeferredExpenseReservesAndAccruals', 'DeferredTaxAssetsValuationAllowance', 'DeferredTaxLiabilitiesGoodwillAndIntangibleAssetsIntangibleAssets', 'DeferredTaxLiabilitiesLeasingArrangements', 'DeferredTaxLiabilitiesPropertyPlantAndEquipment', 'DefinedContributionPlanCostRecognized', 'DefinedContributionPlanEmployerMatchingContributionPercent', 'DefinedContributionPlanMaximumAnnualContributionsPerEmployeeAmount', 'Depreciation', 'DividendsPreferredStock', 'EarningsPerShareBasic', 'EarningsPerShareBasicAndDiluted', 'EarningsPerShareDiluted', 'EffectiveIncomeTaxRateContinuingOperations', 'EffectiveIncomeTaxRateReconciliationAtFederalStatutoryIncomeTaxRate', 'EffectiveIncomeTaxRateReconciliationChangeInDeferredTaxAssetsValuationAllowance', 'EffectiveIncomeTaxRateReconciliationChangeInEnactedTaxRate', 'EffectiveIncomeTaxRateReconciliationNondeductibleExpenseResearchAndDevelopment', 'EffectiveIncomeTaxRateReconciliationNondeductibleExpenseShareBasedCompensationCost', 'EffectiveIncomeTaxRateReconciliationOtherAdjustments', 'EffectiveIncomeTaxRateReconciliationShareBasedCompensationExcessTaxBenefitAmount', 'EffectiveIncomeTaxRateReconciliationStateAndLocalIncomeTaxes', 'EmployeeRelatedLiabilitiesCurrent', 'EscrowDeposit', 'FairValueAdjustmentOfWarrants', 'FinancialLiabilitiesFairValueDisclosure', 'FiniteLivedIntangibleAssetsAccumulatedAmortization', 'FiniteLivedIntangibleAssetsAmortizationExpenseNextTwelveMonths', 'FiniteLivedIntangibleAssetsAmortizationExpenseRemainderOfFiscalYear', 'FiniteLivedIntangibleAssetsAmortizationExpenseYearFour', 'FiniteLivedIntangibleAssetsAmortizationExpenseYearThree', 'FiniteLivedIntangibleAssetsAmortizationExpenseYearTwo', 'FiniteLivedIntangibleAssetsGross', 'FiniteLivedIntangibleAssetsNet', 'ForeignCurrencyTransactionGainLossBeforeTax', 'GainLossOnSaleOfPropertyPlantEquipment', 'GeneralAndAdministrativeExpense', 'Goodwill', 'GoodwillImpairmentLoss', 'GrossProfit', 'ImpairmentOfLeasehold', 'ImpairmentOfLongLivedAssetsHeldForUse', 'IncomeLossFromContinuingOperationsBeforeIncomeTaxesDomestic', 'IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest', 'IncomeLossFromContinuingOperationsBeforeIncomeTaxesForeign', 'IncomeTaxExpenseBenefit', 'IncomeTaxesPaid', 'IncreaseDecreaseInAccountsPayable', 'IncreaseDecreaseInAccountsReceivable', 'IncreaseDecreaseInAccruedLiabilitiesAndOtherOperatingLiabilities', 'IncreaseDecreaseInCommodityContractAssetsAndLiabilities', 'IncreaseDecreaseInDeferredRevenue', 'IncreaseDecreaseInPrepaidDeferredExpenseAndOtherAssets', 'IncreaseDecreaseInRestrictedCash', 'IncreaseInRestrictedCash', 'InterestExpense', 'InterestPaidNet', 'IssuanceOfStockAndWarrantsForServicesOrClaims', 'LesseeOperatingLeaseLiabilityPaymentsDue', 'LesseeOperatingLeaseLiabilityPaymentsDueAfterYearFive', 'LesseeOperatingLeaseLiabilityPaymentsDueNextTwelveMonths', 'LesseeOperatingLeaseLiabilityPaymentsDueYearFive', 'LesseeOperatingLeaseLiabilityPaymentsDueYearFour', 'LesseeOperatingLeaseLiabilityPaymentsDueYearThree', 'LesseeOperatingLeaseLiabilityPaymentsDueYearTwo', 'LesseeOperatingLeaseLiabilityPaymentsRemainderOfFiscalYear', 'LesseeOperatingLeaseLiabilityUndiscountedExcessAmount', 'LessorOperatingLeasePaymentsToBeReceived', 'LettersOfCreditOutstandingAmount', 'Liabilities', 'LiabilitiesAndStockholdersEquity', 'LiabilitiesCurrent', 'LineOfCredit', 'LineOfCreditFacilityMaximumBorrowingCapacity', 'LongTermDebt', 'LongTermDebtCurrent', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInNextTwelveMonths', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInYearFour', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInYearThree', 'LongTermDebtMaturitiesRepaymentsOfPrincipalInYearTwo', 'LongTermDebtNoncurrent', 'LossContingencyAccrualAtCarryingValue', 'MarketableSecuritiesCurrent', 'MoneyMarketFundsAtCarryingValue', 'NetCashProvidedByUsedInFinancingActivities', 'NetCashProvidedByUsedInInvestingActivities', 'NetCashProvidedByUsedInOperatingActivities', 'NetIncomeLoss', 'NetIncomeLossAvailableToCommonStockholdersBasic', 'NumberOfOperatingSegments', 'NumberOfReportableSegments', 'OperatingExpenses', 'OperatingIncomeLoss', 'OperatingLeaseCost', 'OperatingLeaseImpairmentLoss', 'OperatingLeaseLiability', 'OperatingLeaseLiabilityCurrent', 'OperatingLeaseLiabilityNoncurrent', 'OperatingLeasePayments', 'OperatingLeaseRightOfUseAsset', 'OperatingLeaseRightOfUseAssetAmortizationExpense', 'OperatingLeasesFutureMinimumPaymentsDue', 'OperatingLeasesFutureMinimumPaymentsDueCurrent', 'OperatingLeasesFutureMinimumPaymentsDueFutureMinimumSubleaseRentals', 'OperatingLeasesFutureMinimumPaymentsDueInFiveYears', 'OperatingLeasesFutureMinimumPaymentsDueInFourYears', 'OperatingLeasesFutureMinimumPaymentsDueInThreeYears', 'OperatingLeasesFutureMinimumPaymentsDueInTwoYears', 'OperatingLeasesFutureMinimumPaymentsDueThereafter', 'OperatingLeasesFutureMinimumPaymentsRemainderOfFiscalYear', 'OperatingLeasesRentExpenseNet', 'OperatingLeaseWeightedAverageDiscountRatePercent', 'OtherAccruedLiabilitiesCurrent', 'OtherAssetsNoncurrent', 'OtherLiabilitiesNoncurrent', 'OtherNonoperatingIncomeExpense', 'PaymentsForRepurchaseOfRedeemableConvertiblePreferredStock', 'PaymentsOfDebtIssuanceCosts', 'PaymentsRelatedToTaxWithholdingForShareBasedCompensation', 'PaymentsToAcquireMarketableSecurities', 'PaymentsToAcquirePropertyPlantAndEquipment', 'PaymentsToDevelopSoftware', 'PreferredStockParOrStatedValuePerShare', 'PreferredStockRedemptionPremium', 'PreferredStockSharesAuthorized', 'PrepaidExpenseAndOtherAssetsCurrent', 'ProceedsFromConvertibleDebt', 'ProceedsFromDebtNetOfIssuanceCosts', 'ProceedsFromIssuanceInitialPublicOffering', 'ProceedsFromIssuanceOfDebt', 'ProceedsFromIssuanceOfLongTermDebt', 'ProceedsFromIssuanceOfRedeemableConvertiblePreferredStock', 'ProceedsFromLinesOfCredit', 'ProceedsFromSaleAndMaturityOfMarketableSecurities', 'ProceedsFromStockPlans', 'ProceedsFromWarrantExercises', 'ProfitLoss', 'PropertyPlantAndEquipmentGross', 'PropertyPlantAndEquipmentNet', 'ProvisionForDoubtfulAccounts', 'RepaymentsOfDebt', 'ResearchAndDevelopmentExpense', 'RestrictedCash', 'RestrictedCashCurrent', 'RestrictedCashNoncurrent', 'RetainedEarningsAccumulatedDeficit', 'RevenueFromContractWithCustomerExcludingAssessedTax', 'RevenueRemainingPerformanceObligation', 'RightOfUseAssetObtainedInExchangeForOperatingLeaseLiability', 'SaleOfStockConsiderationReceivedOnTransaction', 'SellingAndMarketingExpense', 'ShareBasedCompensation', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardFairValueAssumptionsExpectedDividendRate', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardNumberOfSharesAvailableForGrant', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsForfeituresInPeriod', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsGrantsInPeriodGross', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsGrantsInPeriodWeightedAverageGrantDateFairValue', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsOutstandingIntrinsicValue', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsOutstandingNumber', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsOutstandingWeightedAverageExercisePrice', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsVestedAndExpectedToVestExercisableAggregateIntrinsicValue', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsVestedAndExpectedToVestExercisableNumber', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsVestedAndExpectedToVestExercisableWeightedAverageExercisePrice', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsVestedAndExpectedToVestOutstandingAggregateIntrinsicValue', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsVestedAndExpectedToVestOutstandingNumber', 'ShareBasedCompensationArrangementByShareBasedPaymentAwardOptionsVestedAndExpectedToVestOutstandingWeightedAverageExercisePrice', 'ShareBasedCompensationArrangementsByShareBasedPaymentAwardOptionsExercisesInPeriodWeightedAverageExercisePrice', 'ShareBasedCompensationArrangementsByShareBasedPaymentAwardOptionsForfeituresInPeriodWeightedAverageExercisePrice', 'ShareBasedCompensationArrangementsByShareBasedPaymentAwardOptionsGrantsInPeriodWeightedAverageExercisePrice', 'ShareBasedGoodsAndNonemployeeServicesTransactionQuantityOfSecuritiesIssued', 'SharebasedCompensationArrangementBySharebasedPaymentAwardOptionsExercisableIntrinsicValue1', 'StockholdersEquity', 'StockIssuedDuringPeriodSharesEmployeeStockPurchasePlans', 'StockIssuedDuringPeriodSharesStockOptionsExercised', 'StockIssuedDuringPeriodValueConversionOfConvertibleSecurities', 'StockIssuedDuringPeriodValueEmployeeStockPurchasePlan', 'StockIssuedDuringPeriodValueNewIssues', 'StockIssuedDuringPeriodValueRestrictedStockAwardForfeitures', 'StockIssuedDuringPeriodValueRestrictedStockAwardGross', 'StockIssuedDuringPeriodValueStockOptionsExercised', 'StockRepurchasedAndRetiredDuringPeriodValue', 'SubleaseIncome', 'TemporaryEquityCarryingAmountAttributableToParent', 'TemporaryEquityEliminationAsPartofReorganization', 'TemporaryEquityLiquidationPreference', 'TemporaryEquityParOrStatedValuePerShare', 'TemporaryEquitySharesAuthorized', 'TemporaryEquitySharesIssued', 'TemporaryEquitySharesOutstanding', 'UndistributedEarningsLossAllocatedToParticipatingSecuritiesBasic', 'UnrecognizedTaxBenefits', 'UnrecognizedTaxBenefitsDecreasesResultingFromCurrentPeriodTaxPositions', 'UnrecognizedTaxBenefitsDecreasesResultingFromPriorPeriodTaxPositions', 'UnrecognizedTaxBenefitsIncomeTaxPenaltiesAndInterestExpense', 'UnrecognizedTaxBenefitsIncreasesResultingFromCurrentPeriodTaxPositions', 'UnrecognizedTaxBenefitsIncreasesResultingFromPriorPeriodTaxPositions', 'UnrecognizedTaxBenefitsReductionsResultingFromLapseOfApplicableStatuteOfLimitations', 'UnrecognizedTaxBenefitsThatWouldImpactEffectiveTaxRate', 'ValuationAllowanceDeferredTaxAssetChangeInAmount', 'VariableLeaseCost', 'WeightedAverageNumberOfDilutedSharesOutstanding', 'WeightedAverageNumberOfShareOutstandingBasicAndDiluted', 'WeightedAverageNumberOfSharesOutstandingBasic', 'AvailableForSaleDebtSecuritiesAccumulatedGrossUnrealizedGainBeforeTax', 'AvailableForSaleDebtSecuritiesAccumulatedGrossUnrealizedLossBeforeTax', 'AvailableForSaleDebtSecuritiesAmortizedCostBasis', 'AvailableForSaleSecuritiesDebtSecurities', 'DeferredTaxLiabilitiesDeferredExpenseDeferredFinancingCosts', 'EffectiveIncomeTaxRateReconciliationTaxCreditsResearch', 'AccumulatedOtherComprehensiveIncomeLossNetOfTax', 'ComprehensiveIncomeNetOfTax', 'DebtConversionConvertedInstrumentRate', 'DebtInstrumentConvertibleConversionPrice1', 'DebtInstrumentConvertibleThresholdConsecutiveTradingDays1', 'DebtInstrumentConvertibleThresholdPercentageOfStockPriceTrigger', 'DebtInstrumentConvertibleThresholdTradingDays', 'DebtInstrumentFaceAmount', 'DebtInstrumentInterestRateStatedPercentage', 'DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPositionLessThan12Months', 'DebtSecuritiesAvailableForSaleUnrealizedLossPosition', 'DeferredFinanceCostsGross', 'HeldToMaturitySecuritiesContinuousUnrealizedLossPositionAccumulatedLoss', 'HeldToMaturitySecuritiesContinuousUnrealizedLossPositionLessThan12MonthsAccumulatedLoss', 'InterestExpenseDebt', 'OtherComprehensiveIncomeAvailableforsaleSecuritiesAdjustmentNetOfTaxPortionAttributableToParent', 'DebtSecuritiesAvailableForSaleAmortizedCostExcludingAccruedInterestAfterAllowanceForCreditLoss', 'DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPosition12MonthsOrLonger', 'DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPosition12MonthsOrLongerAccumulatedLoss', 'DebtSecuritiesAvailableForSaleContinuousUnrealizedLossPositionLessThan12MonthsAccumulatedLoss', 'DebtSecuritiesAvailableForSaleExcludingAccruedInterest', 'DebtSecuritiesAvailableForSaleUnrealizedLossPositionAccumulatedLoss', 'InterestExpenseDebtExcludingAmortization', 'ProvisionForLoanLeaseAndOtherLosses', 'DeferredTaxAssetsTaxCreditCarryforwards', 'DeferredTaxLiabilitiesPrepaidExpenses', 'GainsLossesOnExtinguishmentOfDebt', 'IncrementalCommonSharesAttributableToConversionOfDebtSecurities', 'InterestOnConvertibleDebtNetOfTax', 'NetIncomeLossAvailableToCommonStockholdersDiluted', 'PaymentsOfDebtExtinguishmentCosts', 'PaymentsToAcquireAvailableForSaleSecuritiesDebt', 'ProceedsFromMaturitiesPrepaymentsAndCallsOfAvailableForSaleSecurities', 'ProceedsFromSaleOfAvailableForSaleSecuritiesDebt', 'ProceedsFromStockOptionsExercised', 'IncrementalCommonSharesAttributableToCallOptionsAndWarrants', 'IncrementalCommonSharesAttributableToEquityUnitPurchaseAgreements', 'IncrementalCommonSharesAttributableToShareBasedPaymentArrangements', 'AvailableForSaleSecuritiesDebtMaturitiesAfterOneThroughFiveYearsAmortizedCost', 'AvailableForSaleSecuritiesDebtMaturitiesAfterOneThroughFiveYearsFairValue', 'AvailableForSaleSecuritiesDebtMaturitiesSingleMaturityDate', 'AvailableForSaleSecuritiesDebtMaturitiesSingleMaturityDateAmortizedCostBasis', 'AvailableForSaleSecuritiesDebtMaturitiesWithinOneYearAmortizedCost', 'AvailableForSaleSecuritiesDebtMaturitiesWithinOneYearFairValue', 'EffectiveIncomeTaxRateReconciliationFdiiPercent', 'InterestIncomeExpenseNet', 'PaymentsToAcquireIntangibleAssets', 'StockRepurchaseProgramAuthorizedAmount1', 'PaymentsForRepurchaseOfCommonStock', 'StockRepurchasedDuringPeriodValue', 'StockRepurchaseProgramRemainingAuthorizedRepurchaseAmount1', 'TreasuryStockCommonShares', 'TreasuryStockCommonValue', 'InterestIncomeExpenseNonoperatingNet', 'StockRepurchasedAndRetiredDuringPeriodShares', 'TreasuryStockAcquiredAverageCostPerShare', 'StockRepurchasedDuringPeriodShares', 'BusinessExitCosts1', 'DeferredIncomeTaxAssetsNet', 'DepreciationDepletionAndAmortization', 'EmployeeServiceShareBasedCompensationTaxBenefitFromCompensationExpense', 'GoodwillAcquiredDuringPeriod', 'InvestmentIncomeInterest', 'OtherRestructuringCosts', 'PaymentsForRestructuring', 'PaymentsToAcquireBusinessesNetOfCashAcquired', 'RestructuringAndRelatedCostIncurredCost', 'RestructuringAndRelatedCostNumberOfPositionsEliminatedPeriodPercent', 'RestructuringReserve', 'SeveranceCosts1', 'OtherComprehensiveIncomeLossAvailableForSaleSecuritiesAdjustmentNetOfTax', 'TaxesPayableCurrent', 'BusinessCombinationAcquisitionRelatedCosts', 'BusinessCombinationContingentConsiderationLiability', 'DeferredTaxAssetsGoodwillAndIntangibleAssets', 'EffectiveIncomeTaxRateReconciliationFdiiAmount', 'EffectiveIncomeTaxRateReconciliationNondeductibleExpenseOther', 'EffectiveIncomeTaxRateReconciliationTaxContingencies', 'EmployeeServiceShareBasedCompensationNonvestedAwardsTotalCompensationCostNotYetRecognizedStockOptions', 'FiniteLivedIntangibleAssetsAmortizationExpenseYearFive', 'GoodwillPurchaseAccountingAdjustments', 'IncomeTaxesPaidNet', 'IncomeTaxPaidFederalAfterRefundReceived', 'IncomeTaxPaidForeignAfterRefundReceived', 'IncomeTaxReconciliationChangeInDeferredTaxAssetsValuationAllowance', 'IncomeTaxReconciliationIncomeTaxExpenseBenefitAtFederalStatutoryIncomeTaxRate', 'IncomeTaxReconciliationNondeductibleExpenseOther', 'IncomeTaxReconciliationNondeductibleExpenseShareBasedCompensationCost', 'IncomeTaxReconciliationOtherAdjustments', 'IncomeTaxReconciliationStateAndLocalIncomeTaxes', 'IncomeTaxReconciliationTaxContingencies', 'IncomeTaxReconciliationTaxCreditsResearch']
Available units for CIK 0001627475: {'shares', 'USD/shares', 'tradingDay', 'USD', 'Segment', 'pure', 'segment'}

In [3]:
concepts_to_fetch = ['Revenues', 'NetIncomeLoss', 'OperatingExpenses',
                     'Assets', 'Liabilities', 'RevenueFromContractWithCustomerExcludingAssessedTax', 
                     'EarningsPerShareDiluted', 'CommonStockSharesOutstanding',
                     'WeightedAverageNumberOfSharesOutstandingBasic']

In [4]:
def fetch_tickers(url="", table=0, index_col="Symbol", company_col="Security",  cik_col="CIK"):
    # Fetch with proper User-Agent header to avoid 403 error
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
    response = requests.get(url, headers=headers)
    tables = pd.read_html(io.StringIO(response.text))
    index_table = tables[table]  # Use the specified table index
    tickers = index_table[index_col].tolist()
    companies = index_table[company_col].tolist() if company_col in index_table.columns else None
    # cik = index_table[cik_col].tolist() if cik_col in index_table.columns else Nones
    
    # dataframe of tickers, companies, cik
    df = pd.DataFrame({
        'Company': companies,
        'Ticker': tickers,
        # 'CIK': cik
    })

    return df

sp500_url = 'http://en.wikipedia.org/wiki/List_of_S%26P_500_companies'

In [5]:
sp500_df = fetch_tickers(sp500_url)
# convert sp500_df to dictionary with company as key and ticker as value
sp500_tickers = dict(zip(sp500_df['Company'], sp500_df['Ticker']))
sp500_tickers

{'3M': 'MMM',
 'A. O. Smith': 'AOS',
 'Abbott Laboratories': 'ABT',
 'AbbVie': 'ABBV',
 'Accenture': 'ACN',
 'Adobe Inc.': 'ADBE',
 'Advanced Micro Devices': 'AMD',
 'AES Corporation': 'AES',
 'Aflac': 'AFL',
 'Agilent Technologies': 'A',
 'Air Products': 'APD',
 'Airbnb': 'ABNB',
 'Akamai Technologies': 'AKAM',
 'Albemarle Corporation': 'ALB',
 'Alexandria Real Estate Equities': 'ARE',
 'Align Technology': 'ALGN',
 'Allegion': 'ALLE',
 'Alliant Energy': 'LNT',
 'Allstate': 'ALL',
 'Alphabet Inc. (Class A)': 'GOOGL',
 'Alphabet Inc. (Class C)': 'GOOG',
 'Altria': 'MO',
 'Amazon': 'AMZN',
 'Amcor': 'AMCR',
 'Ameren': 'AEE',
 'American Electric Power': 'AEP',
 'American Express': 'AXP',
 'American International Group': 'AIG',
 'American Tower': 'AMT',
 'American Water Works': 'AWK',
 'Ameriprise Financial': 'AMP',
 'Ametek': 'AME',
 'Amgen': 'AMGN',
 'Amphenol': 'APH',
 'Analog Devices': 'ADI',
 'Aon plc': 'AON',
 'APA Corporation': 'APA',
 'Apollo Global Management': 'APO',
 'Apple Inc.': 'AAPL',
 'Applied Materials': 'AMAT',
 'AppLovin': 'APP',
 'Aptiv': 'APTV',
 'Arch Capital Group': 'ACGL',
 'Archer Daniels Midland': 'ADM',
 'Ares Management': 'ARES',
 'Arista Networks': 'ANET',
 'Arthur J. Gallagher & Co.': 'AJG',
 'Assurant': 'AIZ',
 'AT&T': 'T',
 'Atmos Energy': 'ATO',
 'Autodesk': 'ADSK',
 'Automatic Data Processing': 'ADP',
 'AutoZone': 'AZO',
 'AvalonBay Communities': 'AVB',
 'Avery Dennison': 'AVY',
 'Axon Enterprise': 'AXON',
 'Baker Hughes': 'BKR',
 'Ball Corporation': 'BALL',
 'Bank of America': 'BAC',
 'Baxter International': 'BAX',
 'Becton Dickinson': 'BDX',
 'Berkshire Hathaway': 'BRK.B',
 'Best Buy': 'BBY',
 'Bio-Techne': 'TECH',
 'Biogen': 'BIIB',
 'BlackRock': 'BLK',
 'Blackstone Inc.': 'BX',
 'Block, Inc.': 'XYZ',
 'BNY Mellon': 'BK',
 'Boeing': 'BA',
 'Booking Holdings': 'BKNG',
 'Boston Scientific': 'BSX',
 'Bristol Myers Squibb': 'BMY',
 'Broadcom': 'AVGO',
 'Broadridge Financial Solutions': 'BR',
 'Brown & Brown': 'BRO',
 'Brown–Forman': 'BF.B',
 'Builders FirstSource': 'BLDR',
 'Bunge Global': 'BG',
 'BXP, Inc.': 'BXP',
 'C.H. Robinson': 'CHRW',
 'Cadence Design Systems': 'CDNS',
 'Camden Property Trust': 'CPT',
 "Campbell's Company (The)": 'CPB',
 'Capital One': 'COF',
 'Cardinal Health': 'CAH',
 'Carnival': 'CCL',
 'Carrier Global': 'CARR',
 'Carvana': 'CVNA',
 "Casey's": 'CASY',
 'Caterpillar Inc.': 'CAT',
 'Cboe Global Markets': 'CBOE',
 'CBRE Group': 'CBRE',
 'CDW Corporation': 'CDW',
 'Cencora': 'COR',
 'Centene Corporation': 'CNC',
 'CenterPoint Energy': 'CNP',
 'CF Industries': 'CF',
 'Charles River Laboratories': 'CRL',
 'Charles Schwab Corporation': 'SCHW',
 'Charter Communications': 'CHTR',
 'Chevron Corporation': 'CVX',
 'Chipotle Mexican Grill': 'CMG',
 'Chubb Limited': 'CB',
 'Church & Dwight': 'CHD',
 'Ciena': 'CIEN',
 'Cigna': 'CI',
 'Cincinnati Financial': 'CINF',
 'Cintas': 'CTAS',
 'Cisco': 'CSCO',
 'Citigroup': 'C',
 'Citizens Financial Group': 'CFG',
 'Clorox': 'CLX',
 'CME Group': 'CME',
 'CMS Energy': 'CMS',
 'Coca-Cola Company (The)': 'KO',
 'Cognizant': 'CTSH',
 'Coherent Corp.': 'COHR',
 'Coinbase': 'COIN',
 'Colgate-Palmolive': 'CL',
 'Comcast': 'CMCSA',
 'Comfort Systems USA': 'FIX',
 'Conagra Brands': 'CAG',
 'ConocoPhillips': 'COP',
 'Consolidated Edison': 'ED',
 'Constellation Brands': 'STZ',
 'Constellation Energy': 'CEG',
 'Cooper Companies (The)': 'COO',
 'Copart': 'CPRT',
 'Corning Inc.': 'GLW',
 'Corpay': 'CPAY',
 'Corteva': 'CTVA',
 'CoStar Group': 'CSGP',
 'Costco': 'COST',
 'Coterra': 'CTRA',
 'CRH plc': 'CRH',
 'CrowdStrike': 'CRWD',
 'Crown Castle': 'CCI',
 'CSX Corporation': 'CSX',
 'Cummins': 'CMI',
 'CVS Health': 'CVS',
 'Danaher Corporation': 'DHR',
 'Darden Restaurants': 'DRI',
 'Datadog': 'DDOG',
 'DaVita': 'DVA',
 'Deckers Brands': 'DECK',
 'Deere & Company': 'DE',
 'Dell Technologies': 'DELL',
 'Delta Air Lines': 'DAL',
 'Devon Energy': 'DVN',
 'Dexcom': 'DXCM',
 'Diamondback Energy': 'FANG',
 'Digital Realty': 'DLR',
 'Dollar General': 'DG',
 'Dollar Tree': 'DLTR',
 'Dominion Energy': 'D',
 "Domino's": 'DPZ',
 'DoorDash': 'DASH',
 'Dover Corporation': 'DOV',
 'Dow Inc.': 'DOW',
 'D. R. Horton': 'DHI',
 'DTE Energy': 'DTE',
 'Duke Energy': 'DUK',
 'DuPont': 'DD',
 'Eaton Corporation': 'ETN',
 'eBay Inc.': 'EBAY',
 'EchoStar': 'SATS',
 'Ecolab': 'ECL',
 'Edison International': 'EIX',
 'Edwards Lifesciences': 'EW',
 'Electronic Arts': 'EA',
 'Elevance Health': 'ELV',
 'Emcor': 'EME',
 'Emerson Electric': 'EMR',
 'Entergy': 'ETR',
 'EOG Resources': 'EOG',
 'EPAM Systems': 'EPAM',
 'EQT Corporation': 'EQT',
 'Equifax': 'EFX',
 'Equinix': 'EQIX',
 'Equity Residential': 'EQR',
 'Erie Indemnity': 'ERIE',
 'Essex Property Trust': 'ESS',
 'Estée Lauder Companies (The)': 'EL',
 'Everest Group': 'EG',
 'Evergy': 'EVRG',
 'Eversource Energy': 'ES',
 'Exelon': 'EXC',
 'Expand Energy': 'EXE',
 'Expedia Group': 'EXPE',
 'Expeditors International': 'EXPD',
 'Extra Space Storage': 'EXR',
 'ExxonMobil': 'XOM',
 'F5, Inc.': 'FFIV',
 'FactSet': 'FDS',
 'Fair Isaac': 'FICO',
 'Fastenal': 'FAST',
 'Federal Realty Investment Trust': 'FRT',
 'FedEx': 'FDX',
 'Fidelity National Information Services': 'FIS',
 'Fifth Third Bancorp': 'FITB',
 'First Solar': 'FSLR',
 'FirstEnergy': 'FE',
 'Fiserv': 'FISV',
 'Ford Motor Company': 'F',
 'Fortinet': 'FTNT',
 'Fortive': 'FTV',
 'Fox Corporation (Class A)': 'FOXA',
 'Fox Corporation (Class B)': 'FOX',
 'Franklin Resources': 'BEN',
 'Freeport-McMoRan': 'FCX',
 'Garmin': 'GRMN',
 'Gartner': 'IT',
 'GE Aerospace': 'GE',
 'GE HealthCare': 'GEHC',
 'GE Vernova': 'GEV',
 'Gen Digital': 'GEN',
 'Generac': 'GNRC',
 'General Dynamics': 'GD',
 'General Mills': 'GIS',
 'General Motors': 'GM',
 'Genuine Parts Company': 'GPC',
 'Gilead Sciences': 'GILD',
 'Global Payments': 'GPN',
 'Globe Life': 'GL',
 'GoDaddy': 'GDDY',
 'Goldman Sachs': 'GS',
 'Halliburton': 'HAL',
 'Hartford (The)': 'HIG',
 'Hasbro': 'HAS',
 'HCA Healthcare': 'HCA',
 'Healthpeak Properties': 'DOC',
 'Henry Schein': 'HSIC',
 'Hershey Company (The)': 'HSY',
 'Hewlett Packard Enterprise': 'HPE',
 'Hilton Worldwide': 'HLT',
 'Home Depot (The)': 'HD',
 'Honeywell': 'HON',
 'Hormel Foods': 'HRL',
 'Host Hotels & Resorts': 'HST',
 'Howmet Aerospace': 'HWM',
 'HP Inc.': 'HPQ',
 'Hubbell Incorporated': 'HUBB',
 'Humana': 'HUM',
 'Huntington Bancshares': 'HBAN',
 'Huntington Ingalls Industries': 'HII',
 'IBM': 'IBM',
 'IDEX Corporation': 'IEX',
 'Idexx Laboratories': 'IDXX',
 'Illinois Tool Works': 'ITW',
 'Incyte': 'INCY',
 'Ingersoll Rand': 'IR',
 'Insulet Corporation': 'PODD',
 'Intel': 'INTC',
 'Interactive Brokers': 'IBKR',
 'Intercontinental Exchange': 'ICE',
 'International Flavors & Fragrances': 'IFF',
 'International Paper': 'IP',
 'Intuit': 'INTU',
 'Intuitive Surgical': 'ISRG',
 'Invesco': 'IVZ',
 'Invitation Homes': 'INVH',
 'IQVIA': 'IQV',
 'Iron Mountain': 'IRM',
 'J.B. Hunt': 'JBHT',
 'Jabil': 'JBL',
 'Jack Henry & Associates': 'JKHY',
 'Jacobs Solutions': 'J',
 'Johnson & Johnson': 'JNJ',
 'Johnson Controls': 'JCI',
 'JPMorgan Chase': 'JPM',
 'Kenvue': 'KVUE',
 'Keurig Dr Pepper': 'KDP',
 'KeyCorp': 'KEY',
 'Keysight Technologies': 'KEYS',
 'Kimberly-Clark': 'KMB',
 'Kimco Realty': 'KIM',
 'Kinder Morgan': 'KMI',
 'KKR & Co.': 'KKR',
 'KLA Corporation': 'KLAC',
 'Kraft Heinz': 'KHC',
 'Kroger': 'KR',
 'L3Harris': 'LHX',
 'Labcorp': 'LH',
 'Lam Research': 'LRCX',
 'Las Vegas Sands': 'LVS',
 'Leidos': 'LDOS',
 'Lennar': 'LEN',
 'Lennox International': 'LII',
 'Lilly (Eli)': 'LLY',
 'Linde plc': 'LIN',
 'Live Nation Entertainment': 'LYV',
 'Lockheed Martin': 'LMT',
 'Loews Corporation': 'L',
 "Lowe's": 'LOW',
 'Lululemon Athletica': 'LULU',
 'Lumentum': 'LITE',
 'LyondellBasell': 'LYB',
 'M&T Bank': 'MTB',
 'Marathon Petroleum': 'MPC',
 'Marriott International': 'MAR',
 'Marsh McLennan': 'MRSH',
 'Martin Marietta Materials': 'MLM',
 'Masco': 'MAS',
 'Mastercard': 'MA',
 'McCormick & Company': 'MKC',
 "McDonald's": 'MCD',
 'McKesson Corporation': 'MCK',
 'Medtronic': 'MDT',
 'Merck & Co.': 'MRK',
 'Meta Platforms': 'META',
 'MetLife': 'MET',
 'Mettler Toledo': 'MTD',
 'MGM Resorts': 'MGM',
 'Microchip Technology': 'MCHP',
 'Micron Technology': 'MU',
 'Microsoft': 'MSFT',
 'Mid-America Apartment Communities': 'MAA',
 'Moderna': 'MRNA',
 'Molson Coors Beverage Company': 'TAP',
 'Mondelez International': 'MDLZ',
 'Monolithic Power Systems': 'MPWR',
 'Monster Beverage': 'MNST',
 "Moody's Corporation": 'MCO',
 'Morgan Stanley': 'MS',
 'Mosaic Company (The)': 'MOS',
 'Motorola Solutions': 'MSI',
 'MSCI Inc.': 'MSCI',
 'Nasdaq, Inc.': 'NDAQ',
 'NetApp': 'NTAP',
 'Netflix': 'NFLX',
 'Newmont': 'NEM',
 'News Corp (Class A)': 'NWSA',
 'News Corp (Class B)': 'NWS',
 'NextEra Energy': 'NEE',
 'Nike, Inc.': 'NKE',
 'NiSource': 'NI',
 'Nordson Corporation': 'NDSN',
 'Norfolk Southern': 'NSC',
 'Northern Trust': 'NTRS',
 'Northrop Grumman': 'NOC',
 'Norwegian Cruise Line Holdings': 'NCLH',
 'NRG Energy': 'NRG',
 'Nucor': 'NUE',
 'Nvidia': 'NVDA',
 'NVR, Inc.': 'NVR',
 'NXP Semiconductors': 'NXPI',
 'O’Reilly Automotive': 'ORLY',
 'Occidental Petroleum': 'OXY',
 'Old Dominion': 'ODFL',
 'Omnicom Group': 'OMC',
 'ON Semiconductor': 'ON',
 'Oneok': 'OKE',
 'Oracle Corporation': 'ORCL',
 'Otis Worldwide': 'OTIS',
 'Paccar': 'PCAR',
 'Packaging Corporation of America': 'PKG',
 'Palantir Technologies': 'PLTR',
 'Palo Alto Networks': 'PANW',
 'Paramount Skydance Corporation': 'PSKY',
 'Parker Hannifin': 'PH',
 'Paychex': 'PAYX',
 'PayPal': 'PYPL',
 'Pentair': 'PNR',
 'PepsiCo': 'PEP',
 'Pfizer': 'PFE',
 'PG&E Corporation': 'PCG',
 'Philip Morris International': 'PM',
 'Phillips 66': 'PSX',
 'Pinnacle West Capital': 'PNW',
 'PNC Financial Services': 'PNC',
 'Pool Corporation': 'POOL',
 'PPG Industries': 'PPG',
 'PPL Corporation': 'PPL',
 'Principal Financial Group': 'PFG',
 'Procter & Gamble': 'PG',
 'Progressive Corporation': 'PGR',
 'Prologis': 'PLD',
 'Prudential Financial': 'PRU',
 'Public Service Enterprise Group': 'PEG',
 'PTC Inc.': 'PTC',
 'Public Storage': 'PSA',
 'PulteGroup': 'PHM',
 'Quanta Services': 'PWR',
 'Qualcomm': 'QCOM',
 'Quest Diagnostics': 'DGX',
 'Qnity Electronics': 'Q',
 'Ralph Lauren Corporation': 'RL',
 'Raymond James Financial': 'RJF',
 'RTX Corporation': 'RTX',
 'Realty Income': 'O',
 'Regency Centers': 'REG',
 'Regeneron Pharmaceuticals': 'REGN',
 'Regions Financial Corporation': 'RF',
 'Republic Services': 'RSG',
 'ResMed': 'RMD',
 'Revvity': 'RVTY',
 'Robinhood Markets': 'HOOD',
 'Rockwell Automation': 'ROK',
 'Rollins, Inc.': 'ROL',
 'Roper Technologies': 'ROP',
 'Ross Stores': 'ROST',
 'Royal Caribbean Group': 'RCL',
 'S&P Global': 'SPGI',
 'Salesforce': 'CRM',
 'Sandisk': 'SNDK',
 'SBA Communications': 'SBAC',
 'Schlumberger': 'SLB',
 'Seagate Technology': 'STX',
 'Sempra': 'SRE',
 'ServiceNow': 'NOW',
 'Sherwin-Williams': 'SHW',
 'Simon Property Group': 'SPG',
 'Skyworks Solutions': 'SWKS',
 'J.M. Smucker Company (The)': 'SJM',
 'Smurfit Westrock': 'SW',
 'Snap-on': 'SNA',
 'Solventum': 'SOLV',
 'Southern Company': 'SO',
 'Southwest Airlines': 'LUV',
 'Stanley Black & Decker': 'SWK',
 'Starbucks': 'SBUX',
 'State Street Corporation': 'STT',
 'Steel Dynamics': 'STLD',
 'Steris': 'STE',
 'Stryker Corporation': 'SYK',
 'Supermicro': 'SMCI',
 'Synchrony Financial': 'SYF',
 'Synopsys': 'SNPS',
 'Sysco': 'SYY',
 'T-Mobile US': 'TMUS',
 'T. Rowe Price': 'TROW',
 'Take-Two Interactive': 'TTWO',
 'Tapestry, Inc.': 'TPR',
 'Targa Resources': 'TRGP',
 'Target Corporation': 'TGT',
 'TE Connectivity': 'TEL',
 'Teledyne Technologies': 'TDY',
 'Teradyne': 'TER',
 'Tesla, Inc.': 'TSLA',
 'Texas Instruments': 'TXN',
 'Texas Pacific Land Corporation': 'TPL',
 'Textron': 'TXT',
 'Thermo Fisher Scientific': 'TMO',
 'TJX Companies': 'TJX',
 'TKO Group Holdings': 'TKO',
 'Trade Desk (The)': 'TTD',
 'Tractor Supply': 'TSCO',
 'Trane Technologies': 'TT',
 'TransDigm Group': 'TDG',
 'Travelers Companies (The)': 'TRV',
 'Trimble Inc.': 'TRMB',
 'Truist Financial': 'TFC',
 'Tyler Technologies': 'TYL',
 'Tyson Foods': 'TSN',
 'U.S. Bancorp': 'USB',
 'Uber': 'UBER',
 'UDR, Inc.': 'UDR',
 'Ulta Beauty': 'ULTA',
 'Union Pacific Corporation': 'UNP',
 'United Airlines Holdings': 'UAL',
 'United Parcel Service': 'UPS',
 'United Rentals': 'URI',
 'UnitedHealth Group': 'UNH',
 'Universal Health Services': 'UHS',
 'Valero Energy': 'VLO',
 'Ventas': 'VTR',
 'Veralto': 'VLTO',
 'Verisign': 'VRSN',
 'Verisk Analytics': 'VRSK',
 'Verizon': 'VZ',
 'Vertex Pharmaceuticals': 'VRTX',
 'Vertiv': 'VRT',
 'Viatris': 'VTRS',
 'Vici Properties': 'VICI',
 'Visa Inc.': 'V',
 'Vistra Corp.': 'VST',
 'Vulcan Materials Company': 'VMC',
 'W. R. Berkley Corporation': 'WRB',
 'W. W. Grainger': 'GWW',
 'Wabtec': 'WAB',
 'Walmart': 'WMT',
 'Walt Disney Company (The)': 'DIS',
 'Warner Bros. Discovery': 'WBD',
 'Waste Management': 'WM',
 'Waters Corporation': 'WAT',
 'WEC Energy Group': 'WEC',
 'Wells Fargo': 'WFC',
 'Welltower': 'WELL',
 'West Pharmaceutical Services': 'WST',
 'Western Digital': 'WDC',
 'Weyerhaeuser': 'WY',
 'Williams-Sonoma, Inc.': 'WSM',
 'Williams Companies': 'WMB',
 'Willis Towers Watson': 'WTW',
 'Workday, Inc.': 'WDAY',
 'Wynn Resorts': 'WYNN',
 'Xcel Energy': 'XEL',
 'Xylem Inc.': 'XYL',
 'Yum! Brands': 'YUM',
 'Zebra Technologies': 'ZBRA',
 'Zimmer Biomet': 'ZBH',
 'Zoetis': 'ZTS'}

In [6]:
gig_tickers = {
    'Upwork': "UPWK",
    'Fiverr': "FVRR",
    'Uber': "UBER",
    'Lyft': "LYFT",
    'Doordash': "DASH",
    'Grubhub': "GRUB",
    'Instacart': "CART",
    'Etsy': "ETSY",
    'Shopify': "SHOP",
    'Udemy': "UDMY",
    'Herbalife': "HLF",
    'Primerica': "PRI",
    'Tupperware': "TUP",
    'Avon': "AVP",
    'Nu Skin': "NUS",
    'USANA': "USNA",  
}

# Get the CIK map - returns dict with "ticker" and "title" keys
cik_map = get_cik_map(user_agent='Academic Research Project (gig-economy-capstone@umich.edu)')

# Access ticker -> CIK mapping (keys are uppercase)
ticker_to_cik = cik_map["ticker"]

# Debug: check what keys look like
# sample_tickers = list(ticker_to_cik.keys())[:10]
# print(f"Sample tickers in CIK map: {sample_tickers}")

# Lookup CIKs for our tickers
gig_ciks = {}
for company, ticker in gig_tickers.items():
    lookup = ticker.upper()
    if lookup in ticker_to_cik:
        gig_ciks[ticker] = ticker_to_cik[lookup]
    else:
        print(f"Ticker {ticker} not found in CIK map")

print(f"\nFound CIKs: {gig_ciks}")

sp500_ciks = {}
for company, ticker in sp500_tickers.items():
    lookup = ticker.upper()
    if lookup in ticker_to_cik:
        sp500_ciks[ticker] = ticker_to_cik[lookup]
    else:
        print(f"Ticker {ticker} not found in CIK map")

print(f"\nFound CIKs for S&P 500: {len(sp500_ciks)} companies found")

Ticker GRUB not found in CIK map
Ticker TUP not found in CIK map
Ticker AVP not found in CIK map

Found CIKs: {'UPWK': '1627475', 'FVRR': '1762301', 'UBER': '1543151', 'LYFT': '1759509', 'DASH': '1792789', 'CART': '1579091', 'ETSY': '1370637', 'SHOP': '1594805', 'UDMY': '1607939', 'HLF': '1180262', 'PRI': '1475922', 'NUS': '1021561', 'USNA': '896264'}
Ticker BRK.B not found in CIK map
Ticker BF.B not found in CIK map

Found CIKs for S&P 500: 501 companies found

In [7]:
# recovered missing gig company CIKs by looking up tickers manually
# add missing gig company CIKs to gig_ciks dictionary
gig_ciks['GRUB'] = '0001594109'
gig_ciks['TUP'] = '0001008654'
gig_ciks['AVON'] = '0000008868'
gig_ciks

{'UPWK': '1627475',
 'FVRR': '1762301',
 'UBER': '1543151',
 'LYFT': '1759509',
 'DASH': '1792789',
 'CART': '1579091',
 'ETSY': '1370637',
 'SHOP': '1594805',
 'UDMY': '1607939',
 'HLF': '1180262',
 'PRI': '1475922',
 'NUS': '1021561',
 'USNA': '896264',
 'GRUB': '0001594109',
 'TUP': '0001008654',
 'AVON': '0000008868'}

In [8]:
# to a dictionary with ticker as key and dictionary of ticker and cik
gig_ciks_dict = {ticker: {"ticker": ticker, "cik": str(cik)} for ticker, cik in gig_ciks.items()}
sp500_ciks_dict = {ticker: {"ticker": ticker, "cik": str(cik)} for ticker, cik in sp500_ciks.items()}

In [9]:
def get_company_financials_xbrl(cik, metrics=None):
    if metrics is None:
        metrics = concepts_to_fetch
    
    cik_padded = cik.zfill(10)
    url = f"https://data.sec.gov/api/xbrl/companyfacts/CIK{cik_padded}.json"
    
    headers = {
        'User-Agent': 'Academic Research Project (gig-economy-capstone@umich.edu)',
        'Accept-Encoding': 'gzip, deflate'
    }
    
    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()
        data = response.json()
        
        results = []
        facts = data.get('facts', {})
        
        # US-GAAP namespace contains most financial data
        us_gaap = facts.get('us-gaap', {})
        units = {'Segment', 'shares', 'segment', 'tradingDay', 'pure', 'USD/shares', 'USD'}
        for metric in metrics:
            if metric in us_gaap:
                data_items = []
                for unit in units:
                    if unit in us_gaap[metric].get('units', {}):
                        data_items.extend(us_gaap[metric]['units'][unit])
                for item in data_items:
                    if item.get('form') in ['10-K', '10-Q', '20-F', '6-K']:
                        results.append({
                            'form': item.get('form'),
                            'metric': metric,
                            'value': item.get('val'),
                            'fiscal_year': item.get('fy'),
                            'fiscal_period': item.get('fp'),
                            'filed_date': item.get('filed'),
                            'start_date': item.get('start'),
                            'end_date': item.get('end'),
                            # 'accession_number': item.get('accn'),
                        })
        
        df = pd.DataFrame(results)
        
        if not df.empty:
            # Pivot to get metrics as columns
            df_pivot = df.pivot_table(
                index=['filed_date', 'fiscal_year', 'form', 'fiscal_period'],
                columns='metric',
                values='value',
                aggfunc='first'
            ).reset_index()
            
            return df_pivot
        
        return df
        
    except requests.exceptions.RequestException as e:
        print(f"Error fetching XBRL data for CIK {cik}: {e}")
        return pd.DataFrame()


def get_all_companies_financials(companies=None):
    if companies is None:
        companies = gig_ciks_dict
    
    all_financials = []
    
    for company_name, company_info in companies.items():
        print(f"Fetching financials for {company_name}...")
        time.sleep(0.1)  # Rate limiting
        
        try:
            df = get_company_financials_xbrl(company_info['cik'])
            if not df.empty:
                # df['company'] = company_name
                df['ticker'] = company_info['ticker']
                # df['category'] = company_info['category']
                all_financials.append(df)
                print(f"  Found {len(df)} annual records")
            else:
                print(f"  No financial data found")
        except Exception as e:
            print(f"  Error: {e}")
            continue
    
    if all_financials:
        combined = pd.concat(all_financials, ignore_index=True)
        combined = combined.rename_axis(None, axis=1)
        return combined
    else:
        return pd.DataFrame()

In [10]:
gig_edgar_df_raw = get_all_companies_financials(gig_ciks_dict)
gig_edgar_df_raw = gig_edgar_df_raw[gig_edgar_df_raw['fiscal_year'] != 2026].reset_index(drop=True)
gig_edgar_df_raw.to_csv("../../data/edgar_sec/gig_edgar_sec_raw.csv", index=False)
# gig_edgar_df_raw = pd.read_csv("../../data/edgar_sec/gig_edgar_sec_raw.csv")
gig_edgar_df_raw

Fetching financials for UPWK...
  Found 30 annual records
Fetching financials for FVRR...
  Found 8 annual records
Fetching financials for UBER...
  Found 28 annual records
Fetching financials for LYFT...
  Found 28 annual records
Fetching financials for DASH...
  Found 21 annual records
Fetching financials for CART...
  Found 10 annual records
Fetching financials for ETSY...
  Found 44 annual records
Fetching financials for SHOP...
  Found 6 annual records
Fetching financials for UDMY...
  Found 18 annual records
Fetching financials for HLF...
  Found 63 annual records
Fetching financials for PRI...
  Found 59 annual records
Fetching financials for NUS...
  Found 63 annual records
Fetching financials for USNA...
  Found 59 annual records
Fetching financials for GRUB...
  Found 29 annual records
Fetching financials for TUP...
  Found 54 annual records
Fetching financials for AVON...
  Found 56 annual records

,filed_date,fiscal_year,form,fiscal_period,Assets,CommonStockSharesOutstanding,EarningsPerShareDiluted,Liabilities,NetIncomeLoss,OperatingExpenses,RevenueFromContractWithCustomerExcludingAssessedTax,WeightedAverageNumberOfSharesOutstandingBasic,ticker,Revenues
0,2018-11-08,2018,10-Q,Q3,2.751890e+08,3.374032e+07,NaN,1.400700e+08,1068000.0,98118000.0,1.477930e+08,NaN,UPWK,NaN
1,2019-03-07,2018,10-K,FY,2.751890e+08,3.374032e+07,NaN,1.400700e+08,-16233000.0,116335000.0,1.644450e+08,NaN,UPWK,NaN
2,2019-05-08,2019,10-Q,Q1,3.915730e+08,1.064543e+08,NaN,1.478280e+08,-6784000.0,45610000.0,5.921800e+07,NaN,UPWK,NaN
3,2019-08-07,2019,10-Q,Q2,3.915730e+08,1.064543e+08,NaN,1.478280e+08,-7196000.0,87505000.0,1.218990e+08,NaN,UPWK,NaN
4,2019-11-06,2019,10-Q,Q3,3.915730e+08,1.064543e+08,NaN,1.478280e+08,-14542000.0,134448000.0,1.860120e+08,NaN,UPWK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,2022-05-06,2022,10-Q,Q1,2.307800e+09,1.013400e+02,NaN,3.162500e+09,-63600000.0,NaN,8.504000e+08,NaN,AVON,9.044000e+08
572,2022-08-12,2022,10-Q,Q2,2.307800e+09,1.013400e+02,NaN,3.162500e+09,-125200000.0,NaN,1.715200e+09,NaN,AVON,1.821400e+09
573,2022-11-10,2022,10-Q,Q3,2.307800e+09,1.013400e+02,NaN,3.162500e+09,-167700000.0,NaN,2.443900e+09,NaN,AVON,2.589700e+09
574,2023-03-14,2022,10-K,FY,2.564300e+09,1.013400e+02,NaN,3.162500e+09,-362800000.0,NaN,3.431200e+09,NaN,AVON,3.625200e+09
575,2023-05-15,2023,10-Q,Q1,2.161700e+09,1.013400e+02,NaN,3.402900e+09,-97200000.0,NaN,6.314000e+08,NaN,AVON,6.633000e+08

In [11]:
sp500_edgar_df_raw = get_all_companies_financials(sp500_ciks_dict)
sp500_edgar_df_raw = sp500_edgar_df_raw[sp500_edgar_df_raw['fiscal_year'] != 2026].reset_index(drop=True)
sp500_edgar_df_raw.to_csv("../../data/edgar_sec/sp500_edgar_sec_raw.csv", index=False)

# sp500_edgar_df_raw = pd.read_csv("../../data/edgar_sec/sp500_edgar_sec_raw.csv")

sp500_edgar_df_raw

Fetching financials for MMM...
  Found 67 annual records
Fetching financials for AOS...
  Found 62 annual records
Fetching financials for ABT...
  Found 67 annual records
Fetching financials for ABBV...
  Found 52 annual records
Fetching financials for ACN...
  Found 66 annual records
Fetching financials for ADBE...
  Found 68 annual records
Fetching financials for AMD...
  Found 63 annual records
Fetching financials for AES...
  Found 67 annual records
Fetching financials for AFL...
  Found 66 annual records
Fetching financials for A...
  Found 65 annual records
Fetching financials for APD...
  Found 67 annual records
Fetching financials for ABNB...
  Found 20 annual records
Fetching financials for AKAM...
  Found 65 annual records
Fetching financials for ALB...
  Found 63 annual records
Fetching financials for ARE...
  Found 62 annual records
Fetching financials for ALGN...
  Found 63 annual records
Fetching financials for ALLE...
  Found 48 annual records
Fetching financials for LNT...
  Found 63 annual records
Fetching financials for ALL...
  Found 65 annual records
Fetching financials for GOOGL...
  Found 42 annual records
Fetching financials for GOOG...
  Found 42 annual records
Fetching financials for MO...
  Found 65 annual records
Fetching financials for AMZN...
  Found 67 annual records
Fetching financials for AMCR...
  Found 28 annual records
Fetching financials for AEE...
  Found 67 annual records
Fetching financials for AEP...
  Found 67 annual records
Fetching financials for AXP...
  Found 66 annual records
Fetching financials for AIG...
  Found 65 annual records
Fetching financials for AMT...
  Found 67 annual records
Fetching financials for AWK...
  Found 63 annual records
Fetching financials for AMP...
  Found 67 annual records
Fetching financials for AME...
  Found 67 annual records
Fetching financials for AMGN...
  Found 67 annual records
Fetching financials for APH...
  Found 67 annual records
Fetching financials for ADI...
  Found 67 annual records
Fetching financials for AON...
  Found 67 annual records
Fetching financials for APA...
  Found 20 annual records
Fetching financials for APO...
  Found 16 annual records
Fetching financials for AAPL...
  Found 67 annual records
Fetching financials for AMAT...
  Found 67 annual records
Fetching financials for APP...
  Found 20 annual records
Fetching financials for APTV...
  Found 56 annual records
Fetching financials for ACGL...
  Found 63 annual records
Fetching financials for ADM...
  Found 65 annual records
Fetching financials for ARES...
  Found 48 annual records
Fetching financials for ANET...
  Found 48 annual records
Fetching financials for AJG...
  Found 63 annual records
Fetching financials for AIZ...
  Found 67 annual records
Fetching financials for T...
  Found 69 annual records
Fetching financials for ATO...
  Found 63 annual records
Fetching financials for ADSK...
  Found 68 annual records
Fetching financials for ADP...
  Found 65 annual records
Fetching financials for AZO...
  Found 66 annual records
Fetching financials for AVB...
  Found 67 annual records
Fetching financials for AVY...
  Found 63 annual records
Fetching financials for AXON...
  Found 59 annual records
Fetching financials for BKR...
  Found 35 annual records
Fetching financials for BALL...
  Found 63 annual records
Fetching financials for BAC...
  Found 67 annual records
Fetching financials for BAX...
  Found 67 annual records
Fetching financials for BDX...
  Found 67 annual records
Fetching financials for BBY...
  Found 66 annual records
Fetching financials for TECH...
  Found 62 annual records
Fetching financials for BIIB...
  Found 67 annual records
Fetching financials for BLK...
  Found 6 annual records
Fetching financials for BX...
  Found 63 annual records
Fetching financials for XYZ...
  Found 40 annual records
Fetching financials for BK...
  Found 67 annual records
Fetching financials for BA...
  Found 67 annual records
Fetching financials for BKNG...
  Found 63 annual records
Fetching financials for BSX...
  Found 67 annual records
Fetching financials for BMY...
  Found 67 annual records
Fetching financials for AVGO...
  Found 32 annual records
Fetching financials for BR...
  Found 62 annual records
Fetching financials for BRO...
  Found 63 annual records
Fetching financials for BLDR...
  Found 59 annual records
Fetching financials for BG...
  Found 9 annual records
Fetching financials for BXP...
  Found 67 annual records
Fetching financials for CHRW...
  Found 67 annual records
Fetching financials for CDNS...
  Found 63 annual records
Fetching financials for CPT...
  Found 63 annual records
Fetching financials for CPB...
  Found 66 annual records
Fetching financials for COF...
  Found 66 annual records
Fetching financials for CAH...
  Found 65 annual records
Fetching financials for CCL...
  Found 67 annual records
Fetching financials for CARR...
  Found 24 annual records
Fetching financials for CVNA...
  Found 36 annual records
Fetching financials for CASY...
  Found 64 annual records
Fetching financials for CAT...
  Found 65 annual records
Fetching financials for CBOE...
  Found 59 annual records
Fetching financials for CBRE...
  Found 63 annual records
Fetching financials for CDW...
  Found 58 annual records
Fetching financials for COR...
  Found 67 annual records
Fetching financials for CNC...
  Found 63 annual records
Fetching financials for CNP...
  Found 66 annual records
Fetching financials for CF...
  Found 67 annual records
Fetching financials for CRL...
  Found 63 annual records
Fetching financials for SCHW...
  Found 66 annual records
Fetching financials for CHTR...
  Found 59 annual records
Fetching financials for CVX...
  Found 68 annual records
Fetching financials for CMG...
  Found 63 annual records
Fetching financials for CB...
  Found 67 annual records
Fetching financials for CHD...
  Found 63 annual records
Fetching financials for CIEN...
  Found 63 annual records
Fetching financials for CI...
  Found 29 annual records
Fetching financials for CINF...
  Found 63 annual records
Fetching financials for CTAS...
  Found 63 annual records
Fetching financials for CSCO...
  Found 66 annual records
Fetching financials for C...
  Found 66 annual records
Fetching financials for CFG...
  Found 46 annual records
Fetching financials for CLX...
  Found 66 annual records
Fetching financials for CME...
  Found 66 annual records
Fetching financials for CMS...
  Found 63 annual records
Fetching financials for KO...
  Found 66 annual records
Fetching financials for CTSH...
  Found 67 annual records
Fetching financials for COHR...
  Found 62 annual records
Fetching financials for COIN...
  Found 20 annual records
Fetching financials for CL...
  Found 67 annual records
Fetching financials for CMCSA...
  Found 67 annual records
Fetching financials for FIX...
  Found 59 annual records
Fetching financials for CAG...
  Found 67 annual records
Fetching financials for COP...
  Found 68 annual records
Fetching financials for ED...
  Found 63 annual records
Fetching financials for STZ...
  Found 62 annual records
Fetching financials for CEG...
  Found 16 annual records
Fetching financials for COO...
  Found 63 annual records
Fetching financials for CPRT...
  Found 61 annual records
Fetching financials for GLW...
  Found 67 annual records
Fetching financials for CPAY...
  Found 59 annual records
Fetching financials for CTVA...
  Found 28 annual records
Fetching financials for CSGP...
  Found 59 annual records
Fetching financials for COST...
  Found 66 annual records
Fetching financials for CTRA...
  Found 68 annual records
Fetching financials for CRH...
  Found 9 annual records
Fetching financials for CRWD...
  Found 28 annual records
Fetching financials for CCI...
  Found 64 annual records
Fetching financials for CSX...
  Found 68 annual records
Fetching financials for CMI...
  Found 67 annual records
Fetching financials for CVS...
  Found 67 annual records
Fetching financials for DHR...
  Found 66 annual records
Fetching financials for DRI...
  Found 65 annual records
Fetching financials for DDOG...
  Found 26 annual records
Fetching financials for DVA...
  Found 67 annual records
Fetching financials for DECK...
  Found 62 annual records
Fetching financials for DE...
  Found 67 annual records
Fetching financials for DELL...
  Found 40 annual records
Fetching financials for DAL...
  Found 62 annual records
Fetching financials for DVN...
  Found 67 annual records
Fetching financials for DXCM...
  Found 59 annual records
Fetching financials for FANG...
  Found 53 annual records
Fetching financials for DLR...
  Found 60 annual records
Fetching financials for DG...
  Found 60 annual records
Fetching financials for DLTR...
  Found 63 annual records
Fetching financials for D...
  Found 67 annual records
Fetching financials for DPZ...
  Found 60 annual records
Fetching financials for DASH...
  Found 21 annual records
Fetching financials for DOV...
  Found 67 annual records
Fetching financials for DOW...
  Found 28 annual records
Fetching financials for DHI...
  Found 63 annual records
Fetching financials for DTE...
  Found 65 annual records
Fetching financials for DUK...
  Found 67 annual records
Fetching financials for DD...
  Found 34 annual records
Fetching financials for ETN...
  Found 54 annual records
Fetching financials for EBAY...
  Found 67 annual records
Fetching financials for SATS...
  Found 63 annual records
Fetching financials for ECL...
  Found 67 annual records
Fetching financials for EIX...
  Found 67 annual records
Fetching financials for EW...
  Found 63 annual records
Fetching financials for EA...
  Found 67 annual records
Fetching financials for ELV...
  Found 66 annual records
Fetching financials for EME...
  Found 63 annual records
Fetching financials for EMR...
  Found 67 annual records
Fetching financials for ETR...
  Found 64 annual records
Fetching financials for EOG...
  Found 66 annual records
Fetching financials for EPAM...
  Found 56 annual records
Fetching financials for EQT...
  Found 67 annual records
Fetching financials for EFX...
  Found 64 annual records
Fetching financials for EQIX...
  Found 63 annual records
Fetching financials for EQR...
  Found 67 annual records
Fetching financials for ERIE...
  Found 61 annual records
Fetching financials for ESS...
  Found 63 annual records
Fetching financials for EL...
  Found 62 annual records
Fetching financials for EG...
  Found 62 annual records
Fetching financials for EVRG...
  Found 31 annual records
Fetching financials for ES...
  Found 58 annual records
Fetching financials for EXC...
  Found 65 annual records
Fetching financials for EXE...
  Found 67 annual records
Fetching financials for EXPE...
  Found 63 annual records
Fetching financials for EXPD...
  Found 67 annual records
Fetching financials for EXR...
  Found 63 annual records
Fetching financials for XOM...
  Found 67 annual records
Fetching financials for FFIV...
  Found 63 annual records
Fetching financials for FDS...
  Found 62 annual records
Fetching financials for FICO...
  Found 63 annual records
Fetching financials for FAST...
  Found 67 annual records
Fetching financials for FRT...
  Found 63 annual records
Fetching financials for FDX...
  Found 67 annual records
Fetching financials for FIS...
  Found 67 annual records
Fetching financials for FITB...
  Found 67 annual records
Fetching financials for FSLR...
  Found 67 annual records
Fetching financials for FE...
  Found 68 annual records
Fetching financials for FISV...
  Found 67 annual records
Fetching financials for F...
  Found 67 annual records
Fetching financials for FTNT...
  Found 58 annual records
Fetching financials for FTV...
  Found 39 annual records
Fetching financials for FOXA...
  Found 29 annual records
Fetching financials for FOX...
  Found 29 annual records
Fetching financials for BEN...
  Found 66 annual records
Fetching financials for FCX...
  Found 68 annual records
Fetching financials for GRMN...
  Found 65 annual records
Fetching financials for IT...
  Found 63 annual records
Fetching financials for GE...
  Found 67 annual records
Fetching financials for GEHC...
  Found 12 annual records
Fetching financials for GEV...
  Found 8 annual records
Fetching financials for GEN...
  Found 67 annual records
Fetching financials for GNRC...
  Found 58 annual records
Fetching financials for GD...
  Found 67 annual records
Fetching financials for GIS...
  Found 67 annual records
Fetching financials for GM...
  Found 59 annual records
Fetching financials for GPC...
  Found 67 annual records
Fetching financials for GILD...
  Found 67 annual records
Fetching financials for GPN...
  Found 62 annual records
Fetching financials for GL...
  Found 66 annual records
Fetching financials for GDDY...
  Found 43 annual records
Fetching financials for GS...
  Found 67 annual records
Fetching financials for HAL...
  Found 66 annual records
Fetching financials for HIG...
  Found 65 annual records
Fetching financials for HAS...
  Found 61 annual records
Fetching financials for HCA...
  Found 60 annual records
Fetching financials for DOC...
  Found 67 annual records
Fetching financials for HSIC...
  Found 63 annual records
Fetching financials for HSY...
  Found 67 annual records
Fetching financials for HPE...
  Found 42 annual records
Fetching financials for HLT...
  Found 48 annual records
Fetching financials for HD...
  Found 67 annual records
Fetching financials for HON...
  Found 65 annual records
Fetching financials for HRL...
  Found 63 annual records
Fetching financials for HST...
  Found 67 annual records
Fetching financials for HWM...
  Found 66 annual records
Fetching financials for HPQ...
  Found 65 annual records
Fetching financials for HUBB...
  Found 63 annual records
Fetching financials for HUM...
  Found 67 annual records
Fetching financials for HBAN...
  Found 63 annual records
Fetching financials for HII...
  Found 59 annual records
Fetching financials for IBM...
  Found 67 annual records
Fetching financials for IEX...
  Found 63 annual records
Fetching financials for IDXX...
  Found 63 annual records
Fetching financials for ITW...
  Found 67 annual records
Fetching financials for INCY...
  Found 60 annual records
Fetching financials for IR...
  Found 35 annual records
Fetching financials for PODD...
  Found 59 annual records
Fetching financials for INTC...
  Found 67 annual records
Fetching financials for IBKR...
  Found 60 annual records
Fetching financials for ICE...
  Found 51 annual records
Fetching financials for IFF...
  Found 63 annual records
Fetching financials for IP...
  Found 66 annual records
Fetching financials for INTU...
  Found 66 annual records
Fetching financials for ISRG...
  Found 67 annual records
Fetching financials for IVZ...
  Found 67 annual records
Fetching financials for INVH...
  Found 36 annual records
Fetching financials for IQV...
  Found 52 annual records
Fetching financials for IRM...
  Found 64 annual records
Fetching financials for JBHT...
  Found 63 annual records
Fetching financials for JBL...
  Found 62 annual records
Fetching financials for JKHY...
  Found 61 annual records
Fetching financials for J...
  Found 67 annual records
Fetching financials for JNJ...
  Found 67 annual records
Fetching financials for JCI...
  Found 67 annual records
Fetching financials for JPM...
  Found 67 annual records
Fetching financials for KVUE...
  Found 12 annual records
Fetching financials for KDP...
  Found 64 annual records
Fetching financials for KEY...
  Found 66 annual records
Fetching financials for KEYS...
  Found 45 annual records
Fetching financials for KMB...
  Found 66 annual records
Fetching financials for KIM...
  Found 66 annual records
Fetching financials for KMI...
  Found 58 annual records
Fetching financials for KKR...
  Found 59 annual records
Fetching financials for KLAC...
  Found 61 annual records
Fetching financials for KHC...
  Found 43 annual records
Fetching financials for KR...
  Found 67 annual records
Fetching financials for LHX...
  Found 65 annual records
Fetching financials for LH...
  Found 65 annual records
Fetching financials for LRCX...
  Found 62 annual records
Fetching financials for LVS...
  Found 62 annual records
Fetching financials for LDOS...
  Found 63 annual records
Fetching financials for LEN...
  Found 63 annual records
Fetching financials for LII...
  Found 63 annual records
Fetching financials for LLY...
  Found 67 annual records
Fetching financials for LIN...
  Found 32 annual records
Fetching financials for LYV...
  Found 60 annual records
Fetching financials for LMT...
  Found 67 annual records
Fetching financials for L...
  Found 65 annual records
Fetching financials for LOW...
  Found 66 annual records
Fetching financials for LULU...
  Found 63 annual records
Fetching financials for LITE...
  Found 43 annual records
Fetching financials for LYB...
  Found 58 annual records
Fetching financials for MTB...
  Found 65 annual records
Fetching financials for MPC...
  Found 59 annual records
Fetching financials for MAR...
  Found 67 annual records
Fetching financials for MRSH...
  Found 65 annual records
Fetching financials for MLM...
  Found 63 annual records
Fetching financials for MAS...
  Found 66 annual records
Fetching financials for MA...
  Found 67 annual records
Fetching financials for MKC...
  Found 63 annual records
Fetching financials for MCD...
  Found 67 annual records
Fetching financials for MCK...
  Found 67 annual records
Fetching financials for MDT...
  Found 45 annual records
Fetching financials for MRK...
  Found 67 annual records
Fetching financials for META...
  Found 55 annual records
Fetching financials for MET...
  Found 67 annual records
Fetching financials for MTD...
  Found 63 annual records
Fetching financials for MGM...
  Found 62 annual records
Fetching financials for MCHP...
  Found 66 annual records
Fetching financials for MU...
  Found 63 annual records
Fetching financials for MSFT...
  Found 65 annual records
Fetching financials for MAA...
  Found 63 annual records
Fetching financials for MRNA...
  Found 29 annual records
Fetching financials for TAP...
  Found 67 annual records
Fetching financials for MDLZ...
  Found 66 annual records
Fetching financials for MPWR...
  Found 58 annual records
Fetching financials for MNST...
  Found 63 annual records
Fetching financials for MCO...
  Found 66 annual records
Fetching financials for MS...
  Found 67 annual records
Fetching financials for MOS...
  Found 60 annual records
Fetching financials for MSI...
  Found 66 annual records
Fetching financials for MSCI...
  Found 62 annual records
Fetching financials for NDAQ...
  Found 63 annual records
Fetching financials for NTAP...
  Found 62 annual records
Fetching financials for NFLX...
  Found 67 annual records
Fetching financials for NEM...
  Found 68 annual records
Fetching financials for NWSA...
  Found 50 annual records
Fetching financials for NWS...
  Found 50 annual records
Fetching financials for NEE...
  Found 67 annual records
Fetching financials for NKE...
  Found 67 annual records
Fetching financials for NI...
  Found 64 annual records
Fetching financials for NDSN...
  Found 63 annual records
Fetching financials for NSC...
  Found 66 annual records
Fetching financials for NTRS...
  Found 65 annual records
Fetching financials for NOC...
  Found 67 annual records
Fetching financials for NCLH...
  Found 52 annual records
Fetching financials for NRG...
  Found 66 annual records
Fetching financials for NUE...
  Found 67 annual records
Fetching financials for NVDA...
  Found 67 annual records
Fetching financials for NVR...
  Found 63 annual records
Fetching financials for NXPI...
  Found 32 annual records
Fetching financials for ORLY...
  Found 64 annual records
Fetching financials for OXY...
  Found 67 annual records
Fetching financials for ODFL...
  Found 63 annual records
Fetching financials for OMC...
  Found 66 annual records
Fetching financials for ON...

,filed_date,fiscal_year,form,fiscal_period,Assets,CommonStockSharesOutstanding,EarningsPerShareDiluted,Liabilities,NetIncomeLoss,RevenueFromContractWithCustomerExcludingAssessedTax,Revenues,WeightedAverageNumberOfSharesOutstandingBasic,ticker,OperatingExpenses
0,2009-07-31,2009,10-Q,Q2,2.579300e+10,NaN,2.70,1.548900e+10,1.933000e+09,NaN,NaN,704300000.0,MMM,NaN
1,2009-10-30,2009,10-Q,Q3,2.579300e+10,NaN,4.11,1.548900e+10,2.924000e+09,NaN,NaN,701300000.0,MMM,NaN
2,2010-02-16,2009,10-K,FY,2.579300e+10,693543287.0,5.60,1.548900e+10,4.096000e+09,NaN,NaN,718300000.0,MMM,NaN
3,2010-05-05,2010,10-Q,Q1,2.725000e+10,NaN,0.74,1.394800e+10,5.180000e+08,NaN,NaN,693500000.0,MMM,NaN
4,2010-08-04,2010,10-Q,Q2,2.725000e+10,NaN,1.86,1.394800e+10,1.301000e+09,NaN,NaN,695200000.0,MMM,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29442,2025-02-13,2024,10-K,FY,1.428600e+10,458367358.0,4.49,9.295000e+09,2.114000e+09,NaN,8.080000e+09,468891000.0,ZTS,NaN
29443,2025-05-06,2025,10-Q,Q1,1.423700e+10,448743073.0,1.31,9.467000e+09,5.990000e+08,NaN,2.190000e+09,458000000.0,ZTS,NaN
29444,2025-08-05,2025,10-Q,Q2,1.423700e+10,448743073.0,2.67,9.467000e+09,1.223000e+09,NaN,4.551000e+09,456700000.0,ZTS,NaN
29445,2025-11-04,2025,10-Q,Q3,1.423700e+10,448743073.0,4.18,9.467000e+09,1.905000e+09,NaN,6.939000e+09,455400000.0,ZTS,NaN
29446,2026-02-12,2025,10-K,FY,1.423700e+10,448473073.0,5.07,9.467000e+09,2.344000e+09,NaN,8.544000e+09,461172000.0,ZTS,NaN

In [12]:
print(sp500_edgar_df_raw.isna().sum())

filed_date                                                 0
fiscal_year                                                0
form                                                       0
fiscal_period                                              0
Assets                                                    58
CommonStockSharesOutstanding                           12685
EarningsPerShareDiluted                                 1787
Liabilities                                             9221
NetIncomeLoss                                           3557
RevenueFromContractWithCustomerExcludingAssessedTax    20651
Revenues                                               15365
WeightedAverageNumberOfSharesOutstandingBasic           1949
ticker                                                     0
OperatingExpenses                                      22488
dtype: int64

In [13]:
# Feature engineering
def feature_engineering(df):
    df = df.copy()
    
    # if 'date' column doesn't exist, create it based on 'fiscal_period' and 'fiscal_year'
    if 'date' not in df.columns:
        fiscal_period_mapping = {
            'Q1': '03-31',
            'Q2': '06-30',
            'Q3': '09-30',
            'Q4': '12-31',
            'FY': '12-31'
        }
        
        df['date'] = df['fiscal_period'].map(fiscal_period_mapping).fillna(df['fiscal_period'])
        # use 'fiscal_year' and 'date' to create a proper datetime column
        df['date'] = df.apply(lambda row: f"{row['fiscal_year']}-{row['date']}" if pd.notna(row['fiscal_year']) and pd.notna(row['date']) else pd.NaT, axis=1)
    
    df = df.sort_values(['ticker', 'date'])
    
    # combine all Revenue-related columns into a single 'Revenue' column, preferring 'Revenues' if present
    revenue_cols = [col for col in df.columns if isinstance(col, str) and 'Revenue' in col and col != 'Revenue']
    if revenue_cols:
        # sort so 'Revenues' comes first (highest priority)
        ordered = sorted(revenue_cols, key=lambda c: (c != 'Revenues'))
        df['Revenue'] = df[ordered[0]]
        for col in ordered[1:]:
            df['Revenue'] = df['Revenue'].combine_first(df[col])
        df = df.drop(columns=revenue_cols, errors='ignore')
        
    # fill missing NetIncomeLoss row-by-row where Revenue and OperatingExpenses are available
    if 'Revenue' in df.columns and 'OperatingExpenses' in df.columns:
        df['OperatingExpenses'] = df['OperatingExpenses'].fillna(0)
        calculated = df['Revenue'] - df['OperatingExpenses']
        if 'NetIncomeLoss' in df.columns:
            df['NetIncomeLoss'] = df['NetIncomeLoss'].combine_first(calculated)
        else:
            df['NetIncomeLoss'] = calculated
    
    # combine all SharesOutstanding-related columns into a single 'SharesOutstanding' column, preferring 'WeightedAverageNumberOfSharesOutstandingBasic' if present
    shares_cols = [col for col in df.columns if isinstance(col, str) and 'SharesOutstanding' in col and col != 'SharesOutstanding']
    if shares_cols:
        # sort so 'WeightedAverageNumberOfSharesOutstandingBasic' comes first (highest priority)
        ordered = sorted(shares_cols, key=lambda c: (c != 'WeightedAverageNumberOfSharesOutstandingBasic'))
        df['SharesOutstanding'] = df[ordered[0]]
        for col in ordered[1:]:
            df['SharesOutstanding'] = df['SharesOutstanding'].combine_first(df[col])
        df = df.drop(columns=shares_cols, errors='ignore')
        
    # fill missing EarningsPerShare row-by-row where NetIncomeLoss and SharesOutstanding are available
    if 'NetIncomeLoss' in df.columns and 'SharesOutstanding' in df.columns:
        shares = df['SharesOutstanding'].replace(0, pd.NA)
        calculated_eps = df['NetIncomeLoss'] / shares
        if 'EarningsPerShareDiluted' in df.columns:
            df['EarningsPerShareDiluted'] = df['EarningsPerShareDiluted'].combine_first(calculated_eps)
        else:
            df['EarningsPerShareDiluted'] = calculated_eps
    
    df['Quarter'] = df['fiscal_period'].apply(lambda x: 4 if x == 'FY' else int(x[1]) if pd.notna(x) and x.startswith('Q') else None)
    
    # calculate NetWorth from Assets and Liabilities
    # fill Liabilities with 0 if it's missing but Assets is present, and vice versa, to allow NetWorth calculation
    df['Assets'] = df['Assets'].fillna(0)
    df['Liabilities'] = df['Liabilities'].fillna(0)
    df['NetWorth'] = df['Assets'] - df['Liabilities']
    
    # calculate SharesOutstanding from WeightedAverageNumberOfSharesOutstandingBasic by adjusting for quarter length (assuming basic shares are reported as a weighted average over the fiscal period)
    df['SharesOutstanding'] = df['SharesOutstanding'].abs()
    df['SharesOutstanding'] = df['SharesOutstanding'] * (12/(df['Quarter'] * 3))
    
    # drop Quarter column
    df = df.drop(columns=['Quarter', 'Revenue', 'WeightedAverageNumberOfSharesOutstandingBasic', 'Assets', 'Liabilities', 'OperatingExpenses'], errors='ignore')
        
    # fill nan values per ticker with mean + std * N(0,1) noise for each numeric metric
    numeric_cols = df.select_dtypes(include='number').columns.difference(['fiscal_year'])
    for metric in numeric_cols:
        def fill_with_noise(x):
            n_missing = x.isna().sum()
            if n_missing == 0:
                return x
            mu = x.mean()
            sigma = x.std()
            if pd.isna(mu):
                return x  # no observed values to draw from — leave as NaN
            noise = mu + (sigma if pd.notna(sigma) and sigma > 0 else 0) * np.random.randn(n_missing)
            x = x.copy()
            x[x.isna()] = noise
            return x
        df[metric] = df.groupby('ticker')[metric].transform(fill_with_noise)
    
    # ticker to 1st column
    cols = df.columns.tolist()
    cols.insert(0, cols.pop(cols.index('ticker')))
    cols.insert(1, cols.pop(cols.index('date')))
    df = df[cols]
    
    # limit date range to 2009-2025
    df = df[(df['fiscal_year'] >= 2009) & (df['fiscal_year'] <= 2025)]
    
    return df.reset_index(drop=True)

In [14]:
gig_edgar_copy = gig_edgar_df_raw.copy()

gig_edgar_df = feature_engineering(gig_edgar_copy)

gig_edgar_df.to_csv("../../data/edgar_sec/gig_edgar_sec.csv", index=False)

print(gig_edgar_df.isna().sum())
gig_edgar_df

ticker                     0
date                       0
filed_date                 0
fiscal_year                0
form                       0
fiscal_period              0
EarningsPerShareDiluted    0
NetIncomeLoss              0
SharesOutstanding          0
NetWorth                   0
dtype: int64

,ticker,date,filed_date,fiscal_year,form,fiscal_period,EarningsPerShareDiluted,NetIncomeLoss,SharesOutstanding,NetWorth
0,AVON,2009-06-30,2009-07-30,2009,10-Q,Q2,0.97,420300000.0,1.093611e+09,7.123000e+08
1,AVON,2009-09-30,2009-10-29,2009,10-Q,Q3,1.49,642900000.0,4.662768e+08,7.123000e+08
2,AVON,2009-12-31,2010-02-25,2009,10-K,FY,1.21,530700000.0,4.334700e+08,7.123000e+08
3,AVON,2010-03-31,2010-04-30,2010,10-Q,Q1,0.27,117300000.0,2.119975e+08,1.312600e+09
4,AVON,2010-06-30,2010-07-29,2010,10-Q,Q2,0.46,200200000.0,8.532800e+08,1.312600e+09
...,...,...,...,...,...,...,...,...,...,...
571,USNA,2024-09-30,2024-11-05,2024,10-Q,Q3,2.43,47022000.0,2.571067e+07,6.327570e+08
572,USNA,2025-03-31,2025-05-06,2025,10-Q,Q1,0.86,16537000.0,7.669600e+07,5.863320e+08
573,USNA,2025-06-30,2025-08-05,2025,10-Q,Q2,1.40,26969000.0,3.824600e+07,5.863320e+08
574,USNA,2025-09-30,2025-11-05,2025,10-Q,Q3,1.96,37576000.0,2.547733e+07,5.863320e+08
575,USNA,2025-12-31,2026-03-16,2025,10-K,FY,3.30,63788000.0,1.925000e+07,5.863320e+08

In [15]:
sp500_edgar_copy = sp500_edgar_df_raw.copy()

sp500_edgar_df = feature_engineering(sp500_edgar_copy)

sp500_edgar_df.to_csv("../../data/edgar_sec/sp500_edgar_sec.csv", index=False)

print(sp500_edgar_df.isna().sum())
sp500_edgar_df

ticker                       0
date                         0
filed_date                   0
fiscal_year                  0
form                         0
fiscal_period                0
EarningsPerShareDiluted    761
NetIncomeLoss               65
SharesOutstanding          248
NetWorth                     0
dtype: int64

,ticker,date,filed_date,fiscal_year,form,fiscal_period,EarningsPerShareDiluted,NetIncomeLoss,SharesOutstanding,NetWorth
0,A,2009-12-31,2009-12-21,2009,10-K,FY,1.57,4.288339e+08,3.940000e+02,2.559000e+09
1,A,2010-03-31,2010-03-10,2010,10-Q,Q1,0.18,1.246776e+09,1.404000e+03,2.514000e+09
2,A,2010-06-30,2010-06-07,2010,10-Q,Q2,-0.11,1.006710e+09,6.960000e+02,2.514000e+09
3,A,2010-12-31,2010-12-20,2010,10-K,FY,1.87,9.064356e+08,3.630000e+08,2.514000e+09
4,A,2011-03-31,2011-03-09,2011,10-Q,Q1,0.22,2.189663e+09,1.392000e+03,3.236000e+09
...,...,...,...,...,...,...,...,...,...,...
29440,ZTS,2024-12-31,2025-02-13,2024,10-K,FY,4.49,2.114000e+09,4.688910e+08,4.991000e+09
29441,ZTS,2025-03-31,2025-05-06,2025,10-Q,Q1,1.31,5.990000e+08,1.832000e+09,4.770000e+09
29442,ZTS,2025-06-30,2025-08-05,2025,10-Q,Q2,2.67,1.223000e+09,9.134000e+08,4.770000e+09
29443,ZTS,2025-09-30,2025-11-04,2025,10-Q,Q3,4.18,1.905000e+09,6.072000e+08,4.770000e+09
29444,ZTS,2025-12-31,2026-02-12,2025,10-K,FY,5.07,2.344000e+09,4.611720e+08,4.770000e+09